### ISSUE TITLE
Diffrence between Two Calculator

### ISSUE THREAD

**Issue by MohammadiMajid** [davidtimovski/compound-interest-calculator#1]
Hi David
First of all, thank you very much for sharing this code.
The problem that happened to me is that this data code is different from the site
https://www.investor.gov/financial-tools-calculators/calculators/compound-interest-calculator
  The output is the same for monthly but different for annual.

**Comment by davidtimovski** [comment]
Hello Majid,

At the time when I wrote it I myself had a hard time making my results match different calculators from different websites. I had planned to use multiple ones and test against all of them but what happened was that many of them also produced different results from each other. From what I understand, different financial institutions will calculate compounding interest in a different manner. I believe they can apply the compounding amount at either the beginning or end of a month, and in separate contexts both approaches would make sense.

If you believe that website to have the most correct way of doing the calculation you are free to play around with the code and try and produce a matching result. I had grabbed that formula you see in the CalculatorService from some website that I can't recall right now. I tried to follow it precisely and this is the result it produces. Maybe there's a better formula somewhere the captures the same inputs and outputs that this project is concerned with.

I'm sorry to say I don't have the time to do this research but if you want you are welcome to try yourself and open a PR, or if you're working on your own calculator let me know if you're able to find a better formula.
